---
# Docker Compose removed to eliminate package costs
# Run PowerShell script directly instead:
# pwsh ./apply-cis-vm-hardening.ps1 -vCenter $VCENTER_SERVER -VMName $VM_NAME# Updated Sun Nov  9 12:49:54 CET 2025
# Updated Sun Nov  9 12:52:26 CET 2025
# Updated Sun Nov  9 12:56:27 CET 2025
